import type { Metadata } from "next";
import "./globals.css";
import "@fontsource/poppins"; // Import Poppins font

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="poppins-font">{children}</body>
    </html>
  );
}
